export const IMAGE_PATH = {
  NAV_HOME: '/nav/home',
  NAV_GIVING: '/nav/giving',
  NAV_ACTIVITY: '/nav/activity',
  NAV_MY: '/nav/my',
  ONBOARDING_CHECKIN: '/onboarding/checkin.svg',
  HOME_CHARACTER: '/home/home_charactor.svg',
  HOME_PRAY: '/home/home_pray.svg',
  HOME_GIVING: '/home/home_giving.svg',
  HOME_POINT: '/home/home_point.svg',
  HOME_MAN: '/home/home_man.svg',
  HOME_WOMAN: '/home/home_woman.svg',
  HOME_BABY: '/home/home_baby.svg',
  GIVINGONCE_COMPLETE: '/givingOnce/givingOnce_complete.svg',
};
