import type { Metadata, Viewport } from 'next';
import {
  HanaBold,
  HanaCM,
  HanaHeavy,
  HanaLight,
  HanaMedium,
  HanaRegular,
} from './fonts/fonts';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${HanaLight.variable} ${HanaRegular.variable} ${HanaMedium.variable} ${HanaBold.variable} ${HanaHeavy.variable} ${HanaCM.variable}`}
    >
      <body className="flex h-dvh w-full items-center justify-center overflow-hidden bg-gray-100 antialiased">
        <div className="scrollbar-hide h-full max-h-[852px] w-full max-w-[393px] overflow-y-auto rounded-4xl bg-white p-3 shadow-md">
          {children}
        </div>
      </body>
    </html>
  );
}
