import type { Metadata, Viewport } from 'next';
import {
  HanaBold,
  HanaCM,
  HanaHeavy,
  HanaLight,
  HanaMedium,
  HanaRegular,
} from './fonts/fonts';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

import Nav from '@/components/ui/cmm/Nav';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ko"
      className={`${HanaLight.variable} ${HanaRegular.variable} ${HanaMedium.variable} ${HanaBold.variable} ${HanaHeavy.variable} ${HanaCM.variable}`}
    >
      <body className="flex h-dvh w-full items-center justify-center overflow-hidden bg-gray-100 antialiased">
        {/* 모바일 뷰포트 시뮬레이션 */}
        <div className="relative h-full max-h-[852px] w-full max-w-[393px] overflow-hidden rounded-[40px] bg-hana-bless-bg shadow-2xl shadow-black/20">
          {/* 스크롤 가능한 본문 영역 */}
          <div className="scrollbar-hide h-full overflow-y-auto px-4 pt-4 pb-24">
            {children}
          </div>

          {/* 하단 고정 네비게이션 */}
          <div className="absolute bottom-0 left-0 z-50 w-full">
            <Nav />
          </div>
        </div>
      </body>
    </html>
  );
}
